### PR TITLE
Diff op for laplacian

### PR DESCRIPTION
**Pull request by jwscook**

### CODE REVIEW

**Comment by jwscook** [comment]
@oparry-ukaea can you let me know when you're happy with this to be merged :) thanks very much for your help obviously! The diffusion operator is not a 5 minute task.

**Comment by oparry-ukaea** [comment]
I added some scripts and accompanying files for my own benefit -
If you don't mind those on main then feel free to merge now, otherwise I can make another branch and cherry pick the diffusion op commit.

**Comment by oparry-ukaea** [comment]
Also, it seems to segfault intermittently when using MPI, not sure if that's due to my changes or not

**Comment by jwscook** [comment]
Oh dear. I've only experienced crashes due to the solution blowing up....

**Pull request merged**
